townyworldregen:
    enabled: true
    items-count: 2
    item-1:
        id: 4
        data: 0
        chance: 50
        min: 10
        max: 50
    item-2:
        id: 13
        data: 0
        chance: 50
        min: 5
        max: 25