townyworldregen:
    enabled: true
    items-count: 2
    item-1:
        id: 4
        data: 0
        chance: 50
        remove: 10
    item-2:
        id: 13
        data: 0
        chance: 50
        remove: 5