name: TownyWorldRegen
main: me.kapehh.TownyWorldRegen.TownyWorldRegen
author: kapehh
version: 1.0.0
commands:
    townyworldregen:
      usage: /<command> [args]
      aliases: twr
      description: Example /twr <select [args] / regen> [rect / circle] [x1 z1 x2 z2 / x1 z1 radius]