name: TownyWorldRegen
main: me.kapehh.TownyWorldRegen.TownyWorldRegen
author: kapehh
version: 1.0.0
commands:
    townyworldregen:
      usage: /<command> [args]
      aliases: twr
      description: Example /twr <set / regen> <world> [x1 y1 z1 x2 y2 z2 patternSet / x1 y1 z1 x2 y2 z2]