name: TownyWorldRegen
main: me.kapehh.TownyWorldRegen.TownyWorldRegen
author: kapehh
version: 1.0.0
commands:
    townyregenrect:
      usage: /<command> [args]
      aliases: trrect
      description: Regen rectangle
    townyregencircle:
      usage: /<command> [args]
      aliases: trcirc
      description: Regen circle